name: qt-framework-6-6-core22
base: core22
version: 6.6.1
summary: Qt Framework
description: |
  Qt is a cross-platform application development framework widely used
  for developing software with graphical user interfaces (GUIs) and
  interactive functionality.

grade: stable
confinement: strict

slots:
    qt-framework-6-6-core22:
      interface: content
      read:
        - $SNAP

parts:
  qt-sdk:
    plugin: nil
    stage-snaps: [qt-framework-sdk/6.6/stable]
    override-prime: |
      set -eux
      craftctl default
      find . -type f,l -name "*.h" -exec bash -c "rm -f {}*" \;
      find . -type f,l -name "*.cpp" -exec bash -c "rm -f {}*" \;
  command-chain:
    source: https://github.com/jardon/snapcraft-desktop-integration.git
    source-type: git
    source-branch: qt-framework
    source-subdir: qt-framework
    plugin: make
    make-parameters:
      - PLATFORM_PLUG=$SNAPCRAFT_PROJECT_NAME
    stage-packages:
      - mime-support
      - shared-mime-info
