name: qt-framework
base: core22
version: git
summary: Qt Framework
description: |
  Qt is a cross-platform application development framework widely used
  for developing software with graphical user interfaces (GUIs) and
  interactive functionality.

grade: devel
confinement: strict

parts:
  build-deps:
    plugin: nil
    build-packages:
      # ALL
      - python3-minimal
      - libclang-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - ninja-build
  qt-6-5:
    after: [build-deps]
    plugin: cmake
    source: https://code.qt.io/qt/qt5.git
    source-tag: v6.5.1
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=usr/include/$CRAFT_ARCH_TRIPLET/$CRAFT_PART_NAME
