name: qt-framework
base: core22
version: bundle
summary: Qt Framework
description: |
  Qt is a cross-platform application development framework widely used
  for developing software with graphical user interfaces (GUIs) and
  interactive functionality.

grade: stable
confinement: strict

slots:
    qt-framework:
      interface: content
      read:
        - $SNAP
        - $SNAP/opt

parts:
  qt-sdk:
    plugin: nil
    stage-snaps: [qt-framework-sdk/latest/edge]
    override-prime: |
      set -eux
      craftctl default
      cd $CRAFT_PRIME/opt
      find . -type f,l -name "*.h" -exec bash -c "rm -f {}*" \;
  command-chain:
    source: https://github.com/jardon/snapcraft-desktop-integration.git
    source-type: git
    source-branch: qt-framework
    source-subdir: qt-framework
    plugin: make
    make-parameters:
      - PLATFORM_PLUG=$SNAPCRAFT_PROJECT_NAME
    stage-packages:
      - mime-support
      - shared-mime-info
