name: qt-framework-6-8
base: core22
version: 6.8.0
summary: Qt Framework
description: |
  Qt is a cross-platform application development framework widely used
  for developing software with graphical user interfaces (GUIs) and
  interactive functionality.

grade: stable
confinement: strict

slots:
    qt-framework-6-8:
      interface: content
      read:
        - $SNAP

parts:
  qt-sdk:
    plugin: nil
    stage-snaps: [qt-framework-sdk/6.8/stable]
    stage-packages:
      - bison
      - clang
      - default-libmysqlclient-dev
      - docbook
      - docbook-xml
      - docbook-xsl
      - doxygen
      - firebird-dev
      - flex
      - flite1-dev
      - gperf
      - graphviz
      - libasound2-dev
      - libatspi2.0-dev
      - libb2-dev
      - libclang-dev
      - libcups2-dev
      - libdbus-1-dev
      - libdouble-conversion-dev
      - libdrm-dev
      - libfontconfig-dev
      - libfontconfig1-dev
      - libfreetype-dev
      - libfreetype6-dev
      - libgbm-dev
      - libgl-dev
      - libgl1-mesa-dev
      - libgles-dev
      - libgles2-mesa-dev
      - libglib2.0-dev
      - libglu-dev
      - libglu1-mesa-dev
      - libglx-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgtk-3-dev
      - libharfbuzz-dev
      - libhunspell-dev
      - libicu-dev
      - libinput-dev
      - libjpeg-dev
      - libkrb5-dev
      - liblttng-ust-dev
      - libmd4c-dev
      - libmd4c-html0-dev
      - libmtdev-dev
      - libnss3-dev
      - libopengl-dev
      - libpcre2-dev
      - libpng-dev
      - libpq-dev
      - libproxy-dev
      - libpulse-dev
      - libsctp-dev
      - libsm-dev
      - libsqlite3-dev
      - libssl-dev
      - libsystemd-dev
      - libts-dev
      - libudev-dev
      - libva-dev
      - libwayland-dev
      - libwayland-egl1-mesa
      - libwayland-server0
      - libx11-dev
      - libx11-xcb-dev
      - libxcb-composite0-dev
      - libxcb-cursor-dev
      - libxcb-damage0-dev
      - libxcb-dpms0-dev
      - libxcb-dri2-0-dev
      - libxcb-dri3-dev
      - libxcb-ewmh-dev
      - libxcb-glx0-dev
      - libxcb-icccm4-dev
      - libxcb-image0-dev
      - libxcb-keysyms1-dev
      - libxcb-present-dev
      - libxcb-randr0-dev
      - libxcb-record0-dev
      - libxcb-render-util0-dev
      - libxcb-render0-dev
      - libxcb-res0-dev
      - libxcb-screensaver0-dev
      - libxcb-shape0-dev
      - libxcb-shm0-dev
      - libxcb-sync-dev
      - libxcb-sync0-dev
      - libxcb-util-dev
      - libxcb-xf86dri0-dev
      - libxcb-xfixes0-dev
      - libxcb-xinerama0-dev
      - libxcb-xinput-dev
      - libxcb-xkb-dev
      - libxcb-xrm-dev
      - libxcb-xtest0-dev
      - libxcb-xv0-dev
      - libxcb-xvmc0-dev
      - libxcb1-dev
      - libxcomposite-dev
      - libxcursor-dev
      - libxext-dev
      - libxfixes-dev
      - libxi-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - libxkbfile-dev
      - libxrender-dev
      - libxshmfence-dev
      - libxtst-dev
      - libzstd-dev
      - llvm-dev
      - ninja-build
      - nodejs
      - pkg-config
      - python-pip
      - python2-minimal
      - python3-html5lib
      - python3-minimal
      - unixodbc-dev
      - zlib1g-dev
      - gettext
      - sgml-data
      - libxml2-utils
      - libglvnd-dev
    prime:
      - -lib
      - -usr/lib/systemd
      - -usr/share/bug
      - -usr/share/dbus-1
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/lintian
      - -usr/share/man
      - -usr/lib/*/*.a
    override-stage: |
        craftctl default
        find $CRAFT_STAGE -type f,l -name "*.pc" -exec bash -c "sed -i 's:/build/qt-framework-sdk/stage/:/snap/$CRAFT_PROJECT_NAME/current:g' {}*" \;
        find $CRAFT_STAGE -type f,l -name "*.pc" -exec bash -c "sed -i 's:/root/stage:/snap/$CRAFT_PROJECT_NAME/current:g' {}*" \;
        find $CRAFT_STAGE -type f,l -name "*.pc" -exec bash -c "sed -i 's:libdir=/usr:libdir=/snap/$CRAFT_PROJECT_NAME/current/usr:g' {}*" \;
        find $CRAFT_STAGE -type f,l -name "*.pc" -exec bash -c "sed -i 's:includedir=/usr:includedir=/snap/$CRAFT_PROJECT_NAME/current/usr:g' {}*" \;
    override-prime: |
      set -eux
      craftctl default
      find . -type f,l -name "*.h" -exec bash -c "rm -f {}*" \;
      find . -type f,l -name "*.cpp" -exec bash -c "rm -f {}*" \;
  command-chain:
    source: https://github.com/jardon/snapcraft-desktop-integration.git
    source-type: git
    source-branch: qt-framework
    source-subdir: qt-framework
    plugin: make
    make-parameters:
      - PLATFORM_PLUG=$SNAPCRAFT_PROJECT_NAME
    stage-packages:
      - mime-support
      - shared-mime-info
