name: qt-framework # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '6.5.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Qt Framework
description: |
  Qt is a cross-platform application development framework widely used
  for developing software with graphical user interfaces (GUIs) and
  interactive functionality.


grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  qt6:
    # See 'snapcraft plugins'
    plugin: cmake
    source: https://code.qt.io/qt/qt5.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    build-packages:
      - perl
      - python3-minimal
      - llvm
      - libclang-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - ninja-build
    override-build: |
      INSTALL_DIR=$CRAFT_PART_INSTALL/usr
      # perl init-repository
      mkdir -p $INSTALL_DIR
      mkdir -p qt6-build
      cd qt6-build
      $CRAFT_PART_SRC/configure -no-opengl -prefix $INSTALL_DIR
      cmake --build . --parallel 4
      cmake --install .
